### ISSUE TITLE
想问下，为什么lessVars.locations一定要是绝对路径，不能是相对路径呢？

### ISSUE THREAD

**Issue by jeffacode** [gcdxuzhiwei/less-vars#1]

**Comment by gcdxuzhiwei** [comment]
可以在单独的工作区文件夹里面单独配置文件的绝对路径 // 其实可以相对工作区或当前文件定位，不过不是很好判断我就没做

**Comment by jeffacode** [comment]
嗯，明白了！我是打算把这个配置放到项目脚手架里，如果是相对路径会简单点，绝对路径我得多写几行判断逻辑来自动生成哈哈

**Comment by gcdxuzhiwei** [comment]
如果是项目文件夹中的话可以试试${folder}/color.less这种，如果想../到其他文件夹还是有点难搞
